spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password: ${MYSQL_PASSWORD}
  jpa:
    generate-ddl: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

